import { Inter } from "next/font/google";
import "./globals.css";
import Navber from "@/component/navber";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "To-do App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navber />
        {children}
      </body>
    </html>
  );
}
